### ISSUE TITLE
Merged view

### ISSUE THREAD

**Issue by applethepeanut** [TermiT/Flycut#149] opened 2018-04-04 09:39 UTC
Please allow the option to put all text in a single window and arrow down to the item you which to use rather than having to scroll through a whole bunch of windows, see attached sample from intellij :)
<img width="715" alt="screen shot 2018-04-04 at 10 42 16" src="https://user-images.githubusercontent.com/1702447/38300526-ee1200a2-37f4-11e8-92cc-1022b4aafb08.png">

**Comment by shaleh** [comment] 2018-04-18 21:19
Dupe of #146

**Closed** 2020-01-26 09:04 UTC
