### ISSUE TITLE
Preferences will not save in Sierra

### ISSUE THREAD

**Issue by stjohnsmythe007** [TermiT/Flycut#126] opened 2017-02-01 20:09 UTC
In Sierra, quitting the app wipes out the prefs, unless I am doing something wrong?

**Comment by smathy** [comment] 2017-03-10 19:46
Probably using the AppStore version?  Probable dupe of #115

**Comment by stjohnsmythe007** [comment] 2017-03-29 18:06
YESSS!  Thank you very much for the info!

**Closed** 2020-01-26 08:57 UTC
