### ISSUE TITLE
Provide an alternative to App Store

### ISSUE THREAD

**Issue by MoOx** [TermiT/Flycut#56] opened 2014-07-22 07:29 UTC
I'm using `brew cask` to install softwares (& to automate things) & I would like to create a recipe for that, but I will need a url to get the .app.
Could you use [github releases](https://github.com/TermiT/Flycut/releases) to provide .app directly ?

**Comment by IvanMalison** [comment] 2015-01-06 19:11
Bump... Any chance of this happening?

**Comment by tomwhoiscontrary** [comment] 2015-03-23 10:32
This sound like a duplicate of #38 (which is also still open). Maybe this issue should be merged with that one, or closed as a dupe?

**Comment by TermiT** [comment] 2016-04-03 16:38
https://github.com/TermiT/Flycut/releases

**Closed** 2016-04-03 16:47 UTC
